---
title: Cause Template
timezone: Etc/UTC
collections:
  posts:
    title: Posts
    output: true
  staff_members:
    title: Staff Members
    output: false
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    _options:
      content:
        width: 1880
        height: 1880
- scope:
    path: ''
  values:
    layout: default
url: https://clean-oryx.cloudvent.net
baseurl: 
google_analytics_key: 
logo: "/siteicon.png"
description: Jekyll template with example content for a not-for-profit organisation.
author:
  name: 
  email: 
  twitter: 
social:
  name: Cause Template
  links:
  - https://github.com/CloudCannon/cause-jekyll-template
permalink: pretty
donation_embed: <script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe
  src="https://donorbox.org/embed/give-sheep-the-vote?hide_donation_meter=true" height="685px"
  width="100%" style="max-width:425px; min-width:310px" seamless="seamless" id="dbox-form-embed"
  name="donorbox" frameborder="0" scrolling="no"></iframe>
newsletter_action: "//your-mailchimp-action-url.com"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
